SALES/urls.py
from django.urls import path
from SALES.views_customer import *
from SALES.views_person_in_charge import *
from SALES.views_purchase_requisition import *
from SALES.views_quotation import *
from SALES.views_sales_order import *
from SALES.views_daily_report import *

app_name = "SALES"
urlpatterns = [
    # CUSTOMER GENERAL INFO
    path('customer/list/', customer_list, name="customer_list"),
    path('customer/detail/<str:id>/', customer_detail, name="customer_detail"),
    path('customer/create/', customer_create, name="customer_create"),
    path('customer/update/<str:id>/', customer_update, name="customer_update"),
    # CUSTOMER ADDRESS INFO
    path('customer/address/create/<str:id>/', customer_address_create, name="customer_address_create"),
    path('customer/address/update/<str:id>/', customer_address_update, name="customer_address_update"),
    # CUSTOMER CONTACT PERSON INFO
    path('customer/contact-person/create/<str:id>/', customer_contact_person_create, name="customer_contact_person_create"),
    path('customer/contact-person/update/<str:id>/', customer_contact_person_update, name="customer_contact_person_update"),
    # CUSTOMER PAYMENT TERM INFO
    path('customer/payment-term/create/<str:id>/', customer_payment_term_create, name="customer_payment_term_create"),
    path('customer/payment-term/update/<str:id>/', customer_payment_term_update, name="customer_payment_term_update"),
    #======================================================================================================================================================================================#
    #======================================================================================================================================================================================#
    # PERSON IN CHARGE INFO
    path('person-in-charge/list/', person_in_charge_list, name="person_in_charge_list"),
    path('person-in-charge/create/', person_in_charge_create, name="person_in_charge_create"),
    #======================================================================================================================================================================================#
    #======================================================================================================================================================================================#
    # PURCHASE REQUISITION GENERAL INFO
    path('purchase-requisition/list/', purchase_requisition_list, name="purchase_requisition_list"),
    path('purchase-requisition/detail/<str:id>/', purchase_requisition_detail, name="purchase_requisition_detail"),
    path('purchase-requisition/create/', purchase_requisition_create, name="purchase_requisition_create"),
    path('purchase-requisition/update/before-create/<str:id>/', purchase_requisition_update_before_create, name="purchase_requisition_update_before_create"),
    path('purchase-requisition/update/after-create/<str:id>/', purchase_requisition_update_after_create, name="purchase_requisition_update_after_create"),
    path('purchase-requisition/print/<str:id>/', purchase_requisition_print, name="purchase_requisition_print"),
    # PURCHASE REQUISITION ITEM INFO
    path('purchase-requisition/item/create/<str:id>/', purchase_requisition_item_create, name="purchase_requisition_item_create"),
    path('purchase-requisition/item/create/after-create/<str:id>/', purchase_requisition_item_create_after_create, name="purchase_requisition_item_create_after_create"),
    path('purchase-requisition/item/update/<str:id>/', purchase_requisition_item_update, name="purchase_requisition_item_update"),
    path('purchase-requisition/item/delete/<str:id>/', purchase_requisition_item_delete, name="purchase_requisition_item_delete"),
    #======================================================================================================================================================================================#
    #======================================================================================================================================================================================#
    # QUOTATION GENERAL INFO
    path('quotation/list/', quotation_list, name="quotation_list"),
    path('quotation/detail/<str:id>/', quotation_detail, name="quotation_detail"),
    path('quotation/create/', quotation_create, name="quotation_create"),
    path('quotation/update/before-create/<str:id>/', quotation_update_before_create, name="quotation_update_before_create"),
    path('quotation/update/after-create/<str:id>/', quotation_update_after_create, name="quotation_update_after_create"),
    path('quotation/print/<str:id>/', quotation_print, name="quotation_print"),
    # QUOTATION ITEM INFO
    path('quotation/item/create/<str:id>/', quotation_item_create, name="quotation_item_create"),
    path('quotation/item/create/after-create/<str:id>/', quotation_item_create_after_create, name="quotation_item_create_after_create"),
    path('quotation/item/update/<str:id>/', quotation_item_update, name="quotation_item_update"),
    path('quotation/item/delete/<str:id>/', quotation_item_delete, name="quotation_item_delete"),
    #======================================================================================================================================================================================#
    #======================================================================================================================================================================================#
    # SALES ORDER GENERAL INFO
    path('sales-order/list/', sales_order_list, name="sales_order_list"),
    path('sales-order/detail/<str:id>/', sales_order_detail, name="sales_order_detail"),
    path('sales-order/create/', sales_order_create, name="sales_order_create"),
    path('sales-order/update/before-create/<str:id>/', sales_order_update_before_create, name="sales_order_update_before_create"),
    path('sales-order/update/after-create/<str:id>/', sales_order_update_after_create, name="sales_order_update_after_create"),
    path('sales-order/print/<str:id>/', sales_order_print, name="sales_order_print"),
    # SALES ORDER ITEM INFO
    path('sales-order/item/create/<str:id>/', sales_order_item_create, name="sales_order_item_create"),
    path('sales-order/item/create/after-create/<str:id>/', sales_order_item_create_after_create, name="sales_order_item_create_after_create"),
    path('sales-order/item/update/<str:id>/', sales_order_item_update, name="sales_order_item_update"),
    path('sales-order/item/delete/<str:id>/', sales_order_item_delete, name="sales_order_item_delete"),
    #======================================================================================================================================================================================#
    #======================================================================================================================================================================================#
    # DAILY REPORT GENERAL INFO
    path('daily-report/list/', daily_report_list, name="daily_report_list"),
    path('daily-report/detail/<str:id>/', daily_report_detail, name="daily_report_detail"),
    path('daily-report/create/', daily_report_create, name="daily_report_create"),
    path('daily-report/update/before-create/<str:id>/', daily_report_update_before_create, name="daily_report_update_before_create"),
    path('daily-report/update/after-create/<str:id>/', daily_report_update_after_create, name="daily_report_update_after_create"),
    # DAILY REPORT ITEM INFO
    path('daily-report/item/create/<str:id>/', daily_report_item_create, name="daily_report_item_create"),
]

SALESMAX/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('SETTINGS.urls')),
    path('', include('HUMANRESOURCE.urls')),
    path('', include('PURCHASE.urls')),
    path('', include('SALES.urls')),
    path('', include('WAREHOUSE.urls')),
]

SALES/forms.py
from django import forms
from django.forms import DateInput
from django.utils import timezone

### SALES:: ALL
from SALES.models import *


#========================================================================================================================================================================================================================================================#
#========================================================================================================================================================================================================================================================#
class DateInput(forms.DateInput):
    input_type = 'date'
#========================================================================================================================================================================================================================================================#
#========================================================================================================================================================================================================================================================#
class CustomerModelForm(forms.ModelForm):
    class Meta:
        model   = Customer
        fields  = "__all__"
        widgets = {
            'name'          : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Customer Name'}),
            'description'   : forms.Textarea(attrs={'class': 'form-control', 'rows': 2}),
            'email'         : forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'example@email.com'}),
            'phone'         : forms.TextInput(attrs={'class': 'form-control', 'placeholder': '(+66)_-___-____ / (+66)__-___-____'}),
        }
#========================================================================================================================================================================================================================================================#
#========================================================================================================================================================================================================================================================#
class CustomerAddressModelForm(forms.ModelForm):
    class Meta:
        model   = CustomerAddress
        fields  = "__all__"
        widgets = {
            'customer'      : forms.Select(attrs={'class': 'select2 form-control', 'data-toggle': 'select2'}),
            'address_name'  : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Head Office / Warehouse #1 / Factory #1'}),
            'address_line_1': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address No., Building, Room, Floor'}),
            'address_line_2': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Alley, Road, Industrial Estate'}),
            'sub_district'  : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Sub - District / Tumbol'}),
            'district'      : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'District / Amphoe'}),
            'province'      : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Provice / State / City'}),
            'postal_code'   : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ZIP Code / Postal Code'}),
            'country'       : forms.Select(attrs={'class': 'select2 form-control', 'data-toggle': 'select2'}),
            'phone'         : forms.TextInput(attrs={'class': 'form-control', 'placeholder': '(+66)_-___-____ / (+66)__-___-____'}),
            'fax'           : forms.TextInput(attrs={'class': 'form-control', 'placeholder': '(+66)_-___-____'})
        }
#========================================================================================================================================================================================================================================================#
#========================================================================================================================================================================================================================================================#
class CustomerContactPersonModelForm(forms.ModelForm):
    class Meta:
        model   = CustomerContactPerson
        fields  = "__all__"
        widgets = {
            'customer'      : forms.Select(attrs={'class': 'select2 form-control', 'data-toggle': 'select2'}),
            'fullname'      : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g. John Doe'}),
            'job_title'     : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g. Purchasing Manager'}),
            'phone'         : forms.TextInput(attrs={'class': 'form-control', 'placeholder': '(+66)_-___-____ / (+66)__-___-____'}),
            'email'         : forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'e.g. email@example.com'}),
            'is_active'     : forms.Select(choices=((True, "Yes"), (False, "No")), attrs={'class': 'select2 form-control', 'data-toggle': 'select2'})
        }
#========================================================================================================================================================================================================================================================#
#========================================================================================================================================================================================================================================================#
class CustomerPaymentTermModelForm(forms.ModelForm):
    class Meta:
        model   = CustomerPaymentTerm
        fields  = "__all__"
        widgets = {
            'customer'      : forms.Select(attrs={'class': 'select2 form-control', 'data-toggle': 'select2'}),
            'payment_term'  : forms.Select(attrs={'class': 'select2 form-control', 'data-toggle': 'select2'}),
            'credit_day'    : forms.NumberInput(attrs={'class': 'form-control'}),
            'credit_amount' : forms.NumberInput(attrs={'class': 'form-control'}),
        }
#========================================================================================================================================================================================================================================================#
#========================================================================================================================================================================================================================================================#
#========================================================================================================================================================================================================================================================#
#========================================================================================================================================================================================================================================================#
#========================================================================================================================================================================================================================================================#
#========================================================================================================================================================================================================================================================#
class PersonInChargeModelForm(forms.ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super(PersonInChargeModelForm, self).__init__(*args, **kwargs)
    #     self.fields['sales_reps'].queryset      = Employee.objects.filter(section__in=['', '', ''])
    
    class Meta:
        model   = PersonInCharge
        fields  = "__all__"
        widgets = {
            'customer'      : forms.Select(attrs={'class': 'select2 form-control', 'data-toggle': 'select2'}),
            'sales_reps'    : forms.Select(attrs={'class': 'select2 form-control', 'data-toggle': 'select2'}),
        }
#========================================================================================================================================================================================================================================================#
#========================================================================================================================================================================================================================================================#
class PurchaseRequisitionModelForm(forms.ModelForm):
    class Meta:
        model   = PurchaseRequisition
        fields  = "__all__"
        widgets = {
            'date'                  : forms.DateInput(attrs={'class': 'form-control', 'data-provide': 'datepicker', 'data-date-format': 'yyyy-mm-dd', 'data-date-autoclose': 'true'}),
            'estimate_needed_date'  : forms.DateInput(attrs={'class': 'form-control', 'data-provide': 'datepicker', 'data-date-format': 'yyyy-mm-dd', 'data-date-autoclose': 'true'}),
            'remark'                : forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }
#========================================================================================================================================================================================================================================================#

templates/SALES/purchase_requisition/purchase_requisition_detail.html
{% extends 'MAIN/main.html' %}
{% load static %}
{% load humanize %}

{% block title %} {{ company.brand_name }} | {{ purchase_requisition.id }} Details {% endblock title %}


{% block css %}
    
{% endblock css %}
    

{% block brand %} {{ company.brand_name }} {% endblock brand %}
    

{% block content %}
{% if perms.SALES.view_purchaserequisition %}
<div class="content">
                        
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'SALES:purchase_requisition_list' %}">Purchase Requisition</a></li>
                        <li class="breadcrumb-item active">Details</li>
                    </ol>
                </div>
                <h4 class="page-title"> {{ purchase_requisition.id }} Details </h4>
            </div>
        </div>
    </div>     
    <!-- end page title --> 

    <div class="row justify-content-center">
        <div class="col-lg-7 col-md-10 col-sm-11">

            <div class="horizontal-steps mt-4 mb-4 pb-5">
                <div class="horizontal-steps-content">
                    {% for status in purchase_requisition_status %}
                    
                        {% if last_status_log %}
                            <div class="step-item {% if last_status_log.status.purchase_requisition_status == status.purchase_requisition_status %} current {% else %}{% endif %}">
                                <span> {{ status }} </span>
                            </div>
                        {% else %}
                            <div class="step-item">
                                <span> {{ status }} </span>
                            </div>
                        {% endif %}

                    {% endfor %}
                </div>

                <div class="process-line" style="width: {{ percent }}%;"></div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-xl-6 col-3"></div>
                        <div class="col-xl-2 col-3">
                            <a class="btn btn-outline-secondary btn-block mr-1" href="{% url 'SALES:purchase_requisition_print' purchase_requisition.id %}"><i class="mdi mdi-file-search-outline"></i><span class="d-none d-xl-inline ml-1">Preview</span></a>
                        </div>
                        <div class="col-xl-2 col-3">
                            <a class="btn btn-outline-primary btn-block mr-1" href="{% url 'SALES:purchase_requisition_update_after_create' purchase_requisition.id %}"><i class="mdi mdi-file-edit-outline"></i><span class="d-none d-xl-inline ml-1">Edit</span></a>
                        </div>
                        <div class="col-xl-2 col-3">
                            <button class="btn btn-outline-primary btn-block" data-toggle="modal" data-target="#add-status-modal"><i class="mdi mdi-progress-upload"></i><span class="d-none d-xl-inline ml-1">Add Status</span></button>
                        </div>

                        <div id="add-status-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-header modal-colored-header bg-primary">
                                    <h4 class="modal-title" id="primary-header-modalLabel">Add Status</h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                </div>
                                <div class="modal-content">

                                    <div class="modal-body">

                                        <form class="pl-3 pr-3" action="#" method="POST">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <label>{{ form.purchase_requisition.label }} {% if form.purchase_requisition.field.required %} <span class="text-danger">*</span> {% endif %} </label>
                                                {{ form.purchase_requisition }}
                                            </div>

                                            <div class="form-group">
                                                <label>{{ form.status.label }} {% if form.status.field.required %} <span class="text-danger">*</span> {% endif %} </label>
                                                {{ form.status }}
                                            </div>

                                            <div class="form-group">
                                                <label>{{ form.user.label }} {% if form.user.field.required %} <span class="text-danger">*</span> {% endif %} </label>
                                                {{ form.user }}
                                            </div>

                                            <div class="form-group">
                                                <label>{{ form.remark.label }} {% if form.remark.field.required %} <span class="text-danger">*</span> {% endif %} </label>
                                                {{ form.remark }}
                                            </div>

                                            <div class="form-group text-right">
                                                <button class="btn btn-primary" type="submit">Add Status</button>
                                            </div>

                                        </form>

                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">

                    {% if perms.SALES.add_salesorderitem %}
                        <div class="dropdown float-right">
                            <a href="#" class="dropdown-toggle arrow-none card-drop" data-toggle="dropdown" aria-expanded="false">
                                <i class="mdi mdi-dots-vertical"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                
                                {% if perms.SALES.add_salesorderitem %}
                                <!-- item-->
                                <a href="{% url 'SALES:purchase_requisition_item_create_after_create' purchase_requisition.id %}" class="dropdown-item">Add Item</a>
                                {% endif %}

                            </div>
                        </div>
                    {% endif %}

                    <h4 class="header-title mb-3">Items from Purchase Requisition #{{ purchase_requisition.id }}</h4>

                    <div class="table-responsive">
                        <table class="table table-centered table-hover mb-0">
                            <thead class="thead-light">
                                <tr>
                                    <th>Item</th>
                                    <th class="text-right">Quantity</th>
                                    <th class="text-right">Price</th>
                                    <th style="width: 100px;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                
                                {% for item in purchase_requisition_items %}
                                <tr>
                                    <td><span data-toggle="tooltip"
                                        data-placement="right" title=""
                                        data-original-title="{{ item.product.name }}"> {{ item.product.name|truncatechars:30 }} </span></td>
                                    <td class="text-right"> {{ item.quantity|floatformat:"0"|intcomma }} </td>
                                    <td class="text-right"> {{ item.unit_price|floatformat:"0"|intcomma }} </td>
                                    <td>
                                        
                                        {% if perms.SALES.change_purchase_requisitionitem %}
                                        <a href="{% url 'SALES:purchase_requisition_item_update' item.id %}" class="action-icon"> <i class="mdi mdi-square-edit-outline"></i></a>
                                        {% endif %}
                                        {% if perms.SALES.delete_purchase_requisitionitem %}
                                        <a href="{% url 'SALES:purchase_requisition_item_delete' item.id %}" class="action-icon"> <i class="mdi mdi-delete"></i></a>
                                        {% endif %}
                                            
                                    </td>
                                </tr>
                                {% endfor %}
                                    
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="card">
                <div class="card-body">
                    <h4 class="header-title mb-3">Purchase Requisition Info</h4>

                    <div class="text-center">
                        <i class="mdi mdi-clipboard-file-outline h2 text-muted"></i>
                        <h5><b> {{ purchase_requisition.id }} </b></h5>
                        <p class="mb-1"><b>Date :</b> {{ purchase_requisition.date|date:"d/m/Y" }} </p>
                        <p class="mb-0"><b>Estimate Need Date :</b> {{ purchase_requisition.estimate_needed_date|date:"d/m/Y" }} </p>
                        
                        {% if purchase_requisition.remark %}
                        <p class="mb-0"><b>Remark :</b> {{ purchase_requisition.remark }} </p>
                        {% endif %}
                            
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>
{% else %}
<div class="content">
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Permission Denied</a></li>
                        <li class="breadcrumb-item active">Purchase Requisition</li>
                    </ol>
                </div>
                <h4 class="page-title">Add Purchase Requisition</h4>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="text-center">
                <h3 class="">Permission Denied !</h3>
                <p class="text-muted mt-3">Sorry, you don't have permission to add sales order data.</p>
                <a class="btn btn-primary btn-sm mt-2" href="/"><i class="mdi mdi-home mr-1"></i>Back To Home</a>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock content %}
    

{% block script %}

{% endblock script %}