PURCHASE/urls.py
from django.urls import path
from PURCHASE.views_supplier import *
from PURCHASE.views_product import *
from PURCHASE.views_purchase_order import *

app_name = "PURCHASE"
urlpatterns = [
    # SUPPLIER GENERAL INFO
    path('supplier/list/', supplier_list, name="supplier_list"),
    path('supplier/detail/<str:id>/', supplier_detail, name="supplier_detail"),
    path('supplier/create/', supplier_create, name="supplier_create"),
    path('supplier/update/<str:id>/', supplier_update, name="supplier_update"),
    # SUPPLIER ADDRESS INFO
    path('supplier/address/create/<str:id>/', supplier_address_create, name="supplier_address_create"),
    path('supplier/address/update/<str:id>/', supplier_address_update, name="supplier_address_update"),
    # SUPPLIER CONTACT PERSON INFO
    path('supplier/contact-person/create/<str:id>/', supplier_contact_person_create, name="supplier_contact_person_create"),
    path('supplier/contact-person/update/<str:id>/', supplier_contact_person_update, name="supplier_contact_person_update"),
    # SUPPLIER PAYMENT TERM INFO
    path('supplier/payment-term/create/<str:id>/', supplier_payment_term_create, name="supplier_payment_term_create"),
    path('supplier/payment-term/update/<str:id>/', supplier_payment_term_update, name="supplier_payment_term_update"),
    #======================================================================================================================================================================================#
    #======================================================================================================================================================================================#
    # PRODUCT GENERAL INFO
    path('product/list/', product_list, name="product_list"),
    path('product/detail/<str:id>/', product_detail, name="product_detail"),
    path('product/create/', product_create, name="product_create"),
    path('product/update/<str:id>/', product_update, name="product_update"),
    #======================================================================================================================================================================================#
    #======================================================================================================================================================================================#
    # PURCHASE ORDER
    path('purchase-order/list/', purchase_order_list, name="purchase_order_list"),
    path('purchase-order/detail/<str:id>/', purchase_order_detail, name="purchase_order_detail"),
    path('purchase-order/print/<str:id>/', purchase_order_print, name="purchase_order_print"),
    path('purchase-order/create/', purchase_order_create, name="purchase_order_create"),
    path('purchase-order/update/before-create/<str:id>/', purchase_order_update_before_create, name="purchase_order_update_before_create"),
    path('purchase-order/update/after-create/<str:id>/', purchase_order_update_after_create, name="purchase_order_update_after_create"),
    # PURCHASE ORDER ITEM INFO
    path('purchase-order/item/create/<str:id>/', purchase_order_item_create, name="purchase_order_item_create"),
    path('purchase-order/item/create/after-create/<str:id>/', purchase_order_item_create_after_create, name="purchase_order_item_create_after_create"),
    path('purchase-order/item/update/<str:id>/', purchase_order_item_update, name="purchase_order_item_update"),
    path('purchase-order/item/delete/<str:id>/', purchase_order_item_delete, name="purchase_order_item_delete"),
]

SALES/urls.py
from django.urls import path
from SALES.views_customer import *
from SALES.views_person_in_charge import *
from SALES.views_purchase_requisition import *
from SALES.views_quotation import *
from SALES.views_sales_order import *
from SALES.views_daily_report import *

app_name = "SALES"
urlpatterns = [
    # CUSTOMER GENERAL INFO
    path('customer/list/', customer_list, name="customer_list"),
    path('customer/detail/<str:id>/', customer_detail, name="customer_detail"),
    path('customer/create/', customer_create, name="customer_create"),
    path('customer/update/<str:id>/', customer_update, name="customer_update"),
    # CUSTOMER ADDRESS INFO
    path('customer/address/create/<str:id>/', customer_address_create, name="customer_address_create"),
    path('customer/address/update/<str:id>/', customer_address_update, name="customer_address_update"),
    # CUSTOMER CONTACT PERSON INFO
    path('customer/contact-person/create/<str:id>/', customer_contact_person_create, name="customer_contact_person_create"),
    path('customer/contact-person/update/<str:id>/', customer_contact_person_update, name="customer_contact_person_update"),
    # CUSTOMER PAYMENT TERM INFO
    path('customer/payment-term/create/<str:id>/', customer_payment_term_create, name="customer_payment_term_create"),
    path('customer/payment-term/update/<str:id>/', customer_payment_term_update, name="customer_payment_term_update"),
    #======================================================================================================================================================================================#
    #======================================================================================================================================================================================#
    # PERSON IN CHARGE INFO
    path('person-in-charge/list/', person_in_charge_list, name="person_in_charge_list"),
    path('person-in-charge/create/', person_in_charge_create, name="person_in_charge_create"),
    #======================================================================================================================================================================================#
    #======================================================================================================================================================================================#
    # PURCHASE REQUISITION GENERAL INFO
    path('purchase-requisition/list/', purchase_requisition_list, name="purchase_requisition_list"),
    path('purchase-requisition/detail/<str:id>/', purchase_requisition_detail, name="purchase_requisition_detail"),
    path('purchase-requisition/create/', purchase_requisition_create, name="purchase_requisition_create"),
    path('purchase-requisition/update/before-create/<str:id>/', purchase_requisition_update_before_create, name="purchase_requisition_update_before_create"),
    path('purchase-requisition/update/after-create/<str:id>/', purchase_requisition_update_after_create, name="purchase_requisition_update_after_create"),
    path('purchase-requisition/print/<str:id>/', purchase_requisition_print, name="purchase_requisition_print"),
    # PURCHASE REQUISITION ITEM INFO
    path('purchase-requisition/item/create/<str:id>/', purchase_requisition_item_create, name="purchase_requisition_item_create"),
    path('purchase-requisition/item/create/after-create/<str:id>/', purchase_requisition_item_create_after_create, name="purchase_requisition_item_create_after_create"),
    path('purchase-requisition/item/update/<str:id>/', purchase_requisition_item_update, name="purchase_requisition_item_update"),
    path('purchase-requisition/item/delete/<str:id>/', purchase_requisition_item_delete, name="purchase_requisition_item_delete"),
    #======================================================================================================================================================================================#
    #======================================================================================================================================================================================#
    # QUOTATION GENERAL INFO
    path('quotation/list/', quotation_list, name="quotation_list"),
    path('quotation/detail/<str:id>/', quotation_detail, name="quotation_detail"),
    path('quotation/create/', quotation_create, name="quotation_create"),
    path('quotation/update/before-create/<str:id>/', quotation_update_before_create, name="quotation_update_before_create"),
    path('quotation/update/after-create/<str:id>/', quotation_update_after_create, name="quotation_update_after_create"),
    path('quotation/print/<str:id>/', quotation_print, name="quotation_print"),
    # QUOTATION ITEM INFO
    path('quotation/item/create/<str:id>/', quotation_item_create, name="quotation_item_create"),
    path('quotation/item/create/after-create/<str:id>/', quotation_item_create_after_create, name="quotation_item_create_after_create"),
    path('quotation/item/update/<str:id>/', quotation_item_update, name="quotation_item_update"),
    path('quotation/item/delete/<str:id>/', quotation_item_delete, name="quotation_item_delete"),
    #======================================================================================================================================================================================#
    #======================================================================================================================================================================================#
    # SALES ORDER GENERAL INFO
    path('sales-order/list/', sales_order_list, name="sales_order_list"),
    path('sales-order/detail/<str:id>/', sales_order_detail, name="sales_order_detail"),
    path('sales-order/create/', sales_order_create, name="sales_order_create"),
    path('sales-order/update/before-create/<str:id>/', sales_order_update_before_create, name="sales_order_update_before_create"),
    path('sales-order/update/after-create/<str:id>/', sales_order_update_after_create, name="sales_order_update_after_create"),
    path('sales-order/print/<str:id>/', sales_order_print, name="sales_order_print"),
    # SALES ORDER ITEM INFO
    path('sales-order/item/create/<str:id>/', sales_order_item_create, name="sales_order_item_create"),
    path('sales-order/item/create/after-create/<str:id>/', sales_order_item_create_after_create, name="sales_order_item_create_after_create"),
    path('sales-order/item/update/<str:id>/', sales_order_item_update, name="sales_order_item_update"),
    path('sales-order/item/delete/<str:id>/', sales_order_item_delete, name="sales_order_item_delete"),
    #======================================================================================================================================================================================#
    #======================================================================================================================================================================================#
    # DAILY REPORT GENERAL INFO
    path('daily-report/list/', daily_report_list, name="daily_report_list"),
    path('daily-report/detail/<str:id>/', daily_report_detail, name="daily_report_detail"),
    path('daily-report/create/', daily_report_create, name="daily_report_create"),
    path('daily-report/update/before-create/<str:id>/', daily_report_update_before_create, name="daily_report_update_before_create"),
    path('daily-report/update/after-create/<str:id>/', daily_report_update_after_create, name="daily_report_update_after_create"),
    # DAILY REPORT ITEM INFO
    path('daily-report/item/create/<str:id>/', daily_report_item_create, name="daily_report_item_create"),
]

SALESMAX/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('SETTINGS.urls')),
    path('', include('HUMANRESOURCE.urls')),
    path('', include('PURCHASE.urls')),
    path('', include('SALES.urls')),
    path('', include('WAREHOUSE.urls')),
]

templates/PURCHASE/product/general/product_create.html
{% extends 'MAIN/main.html' %}
{% load static %}


{% block title %} {{ company.brand_name }} | Add Product {% endblock title %}
    

{% block css %}

{% endblock css %}
    

{% block brand %} {{ company.brand_name }} {% endblock brand %}
    

{% block content %}
{% if perms.PURCHASE.add_product %}
<div class="content">
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'PURCHASE:product_list' %}">Product</a></li>
                        <li class="breadcrumb-item active">Add</li>
                    </ol>
                </div>
                <h4 class="page-title">Add Product</h4>
            </div>
        </div>
    </div>     
    <!-- end page title --> 

    <div class="row">
        <div class="col-12">
            <div class="card">
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="card-body">
                        <div class="row">
                            <div class="col-xl-12">
    
                                {% for field in form %}
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label>{{ field.label }} {% if field.field.required %} <span class="text-danger">*</span> {% endif %} </label>
                                                {{ field }}
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
    
                            </div>
                        </div>
                        <div class="row mt-2">
                            <div class="col-sm-6">
                                <a href="{% url 'PURCHASE:supplier_list' %}" class="btn text-muted d-none d-sm-inline-block btn-link font-weight-semibold">
                                    <i class="mdi mdi-arrow-left"></i> Back to Product List 
                                </a>
                            </div>
                            <div class="col-sm-6">
                                <div class="text-sm-right">
                                    <button class="btn btn-primary" type="submit">
                                        <i class="mdi mdi-plus mr-1"></i>Add
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="content">
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Permission Denied</a></li>
                        <li class="breadcrumb-item active">Product</li>
                    </ol>
                </div>
                <h4 class="page-title">Add Product</h4>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="text-center">
                <h3 class="">Permission Denied !</h3>
                <p class="text-muted mt-3">Sorry, you don't have permission to add product data.</p>
                <a class="btn btn-primary btn-sm mt-2" href="/"><i class="mdi mdi-home mr-1"></i>Back To Home</a>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock content %}
    

{% block script %}

{% endblock script %}

templates/PURCHASE/product/general/product_update.html
{% extends 'MAIN/main.html' %}
{% load static %}


{% block title %} {{ company.brand_name }} | Edit Product {% endblock title %}
    

{% block css %}

{% endblock css %}
    

{% block brand %} {{ company.brand_name }} {% endblock brand %}
    

{% block content %}
{% if perms.PURCHASE.change_product %}
<div class="content">
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'PURCHASE:product_list' %}">Product</a></li>
                        <li class="breadcrumb-item active">Edit</li>
                    </ol>
                </div>
                <h4 class="page-title">Edit Product</h4>
            </div>
        </div>
    </div>     
    <!-- end page title --> 

    <div class="row">
        <div class="col-12">
            <div class="card">
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="card-body">
                        <div class="row">
                            <div class="col-xl-12">
    
                                {% for field in form %}
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label>{{ field.label }} {% if field.field.required %} <span class="text-danger">*</span> {% endif %} </label>
                                                {{ field }}
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
    
                            </div>
                        </div>
                        <div class="row mt-2">
                            <div class="col-sm-6">
                                <a href="{% url 'PURCHASE:product_detail' product.id %}" class="btn text-muted d-none d-sm-inline-block btn-link font-weight-semibold">
                                    <i class="mdi mdi-arrow-left"></i> Back to Product Details 
                                </a>
                            </div>
                            <div class="col-sm-6">
                                <div class="text-sm-right">
                                    <button class="btn btn-primary" type="submit">
                                        <i class="mdi mdi-twitter-retweet mr-1"></i>Update
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="content">
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Permission Denied</a></li>
                        <li class="breadcrumb-item active">Product</li>
                    </ol>
                </div>
                <h4 class="page-title">Edit Product</h4>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="text-center">
                <h3 class="">Permission Denied !</h3>
                <p class="text-muted mt-3">Sorry, you don't have permission to edit product data.</p>
                <a class="btn btn-primary btn-sm mt-2" href="/"><i class="mdi mdi-home mr-1"></i>Back To Home</a>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock content %}
    

{% block script %}

{% endblock script %}